name = "jit-extractor"
compatibility_date = "2025-06-01"
pages_build_output_dir = "dist"

# Create these in the Cloudflare dashboard (Workers & Pages -> KV) and paste
# the namespace ids here, or bind them in the Pages project settings UI.
[[kv_namespaces]]
binding = "SCORES"
id = "a3e3281f99644a7cb170a4d680c6763a"

[[kv_namespaces]]
binding = "STATS"
id = "c9056cb7c9404887a28eb1bde2529116"
